version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abnovamart-backend
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/src/generated/prisma
